# Github Action that builds react extension and creates a zip file for deployment, updates the version in manifest.json from package.json and creates a release in github with the zip file
build-extension:
  name: Build Extension
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - name: Install Dependencies
      run: npm install
    - name: Update Manifest
      run: npm run update-manifest
    - name: Build Extension
      run: npm run build
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1
    - name: Zip Extension
      run: zip -r ${{ steps.package-version.outputs.current-version}}.zip build
    - name: Create Release
      run: |
        gh release create ${{ steps.package-version.outputs.current-version}} -F ${{ steps.package-version.outputs.current-version}}.zip
        gh release upload ${{ steps.package-version.outputs.current-version}} ${{ steps.package-version.outputs.current-version}}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}