# Github Action that builds react extension and creates a zip file for deployment, updates the version in manifest.json from package.json and creates a release in github with the zip file
name: Build Extension
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: npm install
      - name: Update Manifest
        run: npm run update-manifest ${{github.ref_name}}
      - name: Build Extension
        run: npm run build
      - name: Zip Extension
        run: zip -r ${{github.ref_name}}.zip ./build/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.ref_name}}.zip
          draft: true
          prerelease: true
          tag_name: ${{github.ref_name}}
          token: ${{secrets.GITHUB_TOKEN}}